export const SCREENS = {
  INDEX: 'index',
  LOGIN: 'login',
  ONBOARDING: 'onboarding',
  REGISTER: 'register',
  TABS: '(tabs)',
  PROTECTED: '(auth-protected)',
  AUTHENTICATE: '(auth)',
  TAB_HOME: 'home',
  TAB_HISTORY: 'history',
  TAB_EXPLORE: 'explore',
  TAB_SETTINGS: 'settings',
  AI: 'ai',
  FORGOT_PASSWORD: 'forgot-password',
  TRACKING_ORDER: 'tracking-order',
  CREATE_ORDER: 'create-order',
  CREATE_ORDER_MAP: 'map',
  CREATE_ORDER_INFORMATION: 'information',
  CREATE_ORDER_PAYMENT: 'payment',
  CREATE_ORDER_COMPLETED: 'completed',
  CREATE_ORDER_VEHICLE: 'vehicle',
};
